### ISSUE TITLE
On the New Listing page Google Maps throws an error

### ISSUE THREAD

**Issue by pdobrescu** [Foundation-For-Intentional-Community/Wordpress-Theme#14]
This is happening on the /directory/new-listing/ page:

<img width="970" alt="image" src="https://user-images.githubusercontent.com/1044106/84452931-87cbaf00-ac2d-11ea-90da-f4c7e18a8dc3.png">

The browser console shows this error:

`Geocoding Service: You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to` http://g.co/dev/maps-no-account, on the https://maps.googleapis.com/maps/api/js?sensor=false&ver=1 request.

**Comment by Photosynthesis** [comment]
Duplicated by #33, fixed by adding API key support to the Formidable Google Maps plugin.
