### ISSUE TITLE
Some new and updated communities are not showing on the map, and map is missing from their listing

### ISSUE THREAD

**Issue by Photosynthesis** [Foundation-For-Intentional-Community/Wordpress-Theme#27]

**Comment by Photosynthesis** [comment]
Looks like updates to directory entries are supposed to trigger an update to the associated MapPress map here: https://github.com/Foundation-For-Intentional-Community/Wordpress-Theme/blob/49a8270dabfb4e38fbad294dea04530954de9524/includes/directory/maps.php#L21

**Comment by Photosynthesis** [comment]
Strangely, it looks like the map on the directory page should be generated by a ```form_to_mappress_latlng``` shortcode, which exists in the directory page content (unless this is a leftover that's now overwritten by the Elm that generates the directory page?). 

In directory post content:  [form_to_mappress_latlng lat1="40.646968" lng1="-111.863496" width="100%" title="<b>Blue Goose Commons</b>" body="985 E 5750 S
          Salt Lake City, Utah, United States"]

Code that's called by this shortcode: https://github.com/Foundation-For-Intentional-Community/Wordpress-Theme/blob/041680176127c59bb4f22954b7248c780ea4ef39/includes/directory/maps.php#L33

**Comment by Photosynthesis** [comment]
@prikhi if you're still available for a quick question: is the content that's in the posts table (eg what's visible at https://www.ic.org/wp-admin/post.php?post=394852&action=edit) in use for anything? My impression was that content for directory pages is getting loaded via Elm and the WP API, but it looks like there is still a lot of code that relates to that posts table content in the theme files (eg shortcodes in https://github.com/Foundation-For-Intentional-Community/Wordpress-Theme/blob/041680176127c59bb4f22954b7248c780ea4ef39/includes/directory/maps.php). Thanks!

**Comment by prikhi** [comment]
Listing details maps are now rendered w/ a webcomponent:

https://github.com/Foundation-For-Intentional-Community/Wordpress-Theme/blob/master/src/Directory/View.elm

https://github.com/Foundation-For-Intentional-Community/Wordpress-Theme/blob/master/src/Map.elm#L39-L48

The directory posts themselves are used to serve the `/directory/<listing-name>` pages, but the `directory_elm` shortcode wipes out everything inside the tags:

https://github.com/Foundation-For-Intentional-Community/Wordpress-Theme/blob/master/includes/directory/shortcodes.php

I think I left the content generation in the Formidable view so that we could easily revert from Elm->Formidable if something went wrong during the switchover.

**Comment by prikhi** [comment]
This script(run via cronjob on old server) was responsible for updating coordinates, because mappress was always problematic:

https://github.com/Foundation-For-Intentional-Community/Wordpress-Scripts/blob/master/exe/DirectoryFixCoordinates.hs

**Comment by Photosynthesis** [comment]
Okay, many thanks for the quick reply @prikhi. Puzzling thing in this case is that the coordinates are appearing in the post content, in the mapppress shortcode! But I guess that might still be there from when the listing was originally generated. Thanks for your clarification.

**Comment by prikhi** [comment]
Yeah, whenever a listing is saved, formidable regenerates the Directory post.
The post content is set by one of the formidable views.

**Comment by Photosynthesis** [comment]
Puzzle: for some listings, such as [this one](https://www.ic.org/directory/miletus/), the map is missing from the listing, but formidable has the coordinates (can be seen here: https://www.ic.org/wp-admin/admin.php?page=formidable-entries&frm_action=show&id=265566). 

Looking at the DB, the coordinates don't seem to exist in the frm_item_metas (eg `SELECT * FROM `3uOgy46w_frm_item_metas` WHERE item_id = 265566`)

Formidable is getting the coordinates from somewhere.    Where?

**Comment by prikhi** [comment]
Check the lat/lng fields specifically? The edit page seems to have values for them.

**Comment by Photosynthesis** [comment]
>  The edit page seems to have values for them.

That's the weird part. It appears in the form, but records for that field and item don't seem to exist in the DB, unless I'm missing something. Looking for the Lat field, for example, gives no results (`SELECT * FROM 3uOgy46w_frm_item_metas WHERE field_id = 684 AND item_id = 265566`).

**Comment by Photosynthesis** [comment]
To test, I manually added the lat and lon form_item_meta records, and now the map is working properly on that listing. 

It remains a mystery where Formidable was getting the coordinates from.

**Comment by Photosynthesis** [comment]
This was eventually resolved with a cron script (in the directory plugin), replacing the previous Haskell script. It remains unclear where coordinates that appear in Formidable for these communities were coming from, when the Formidable data in the DB was missing.
