### ISSUE TITLE
Add number of items to shopping cart icon

### ISSUE THREAD

**Issue by Photosynthesis** [Foundation-For-Intentional-Community/Wordpress-Theme#36]
The cart icon in the upper right should show the number of items currently in the cart.

**Comment by resbraga** [comment]
https://wordpress.org/plugins/popup-notices-for-woocommerce/
https://wordpress.org/plugins/added-to-cart-popup-woocommerce/

or

https://www.skyverge.com/blog/display-woocommerce-cart-notices/

**Comment by resbraga** [comment]
![image](https://user-images.githubusercontent.com/8763832/97810750-e503e380-1c54-11eb-98d3-fc45f87ff985.png)

**Comment by Photosynthesis** [comment]
Notices solved the motivation for this issue. Thanks @resbraga. Closing.
